// StyleSnap — animated style-guide page preview.
// 3 stacked rotated pages; the front straightens on hover.
// Floating badge bottom-right shows "19 pages · ready in 47s".

export function PdfMockup() {
  return (
    <div className="pdf-mock">
      <div className="pdf-page pdf-page-3" />
      <div className="pdf-page pdf-page-2" />
      <div className="pdf-page">
        <div className="pdf-content">
          <div>
            <div className="pdf-cover-domain">stripe.com</div>
            <div className="pdf-cover-title">Brand &amp; design style guide</div>
            <div className="pdf-cover-sub">Generated by StyleSnap · v1.0</div>
          </div>

          <div className="pdf-section-title">2.2 — color palette</div>
          <div className="pdf-color-row">
            {[
              { hex: '#021A2E', name: 'Primary' },
              { hex: '#014379', name: 'Secondary' },
              { hex: '#0D91FD', name: 'Accent' },
              { hex: '#374151', name: 'Text' },
              { hex: '#F9FAFB', name: 'Surface' },
            ].map(({ hex, name }) => (
              <div key={hex} className="pdf-color-cell">
                <div className="pdf-swatch" style={{ background: hex }} />
                <div className="pdf-color-name">{name}</div>
                <div className="pdf-color-hex">{hex}</div>
              </div>
            ))}
          </div>

          <div className="pdf-section-title">2.3 — typography</div>
          <div className="pdf-type-row">
            <div className="pdf-type-h1">Heading 1</div>
            <div className="pdf-type-h2">Heading 2</div>
            <div className="pdf-type-h3">Heading 3</div>
            <div className="pdf-type-body">
              Body text looks like this, with comfortable readability for paragraphs of any reasonable length.
            </div>
            <div className="pdf-type-cap">Caption text for smaller details and meta.</div>
          </div>

          <div className="pdf-footer">
            <span>stylesnap.sh / r / 9kR2vH</span>
            <span>page 04 / 19</span>
          </div>
        </div>
      </div>
      <div className="pdf-badge">
        <span className="dot" />
        <span>19 pages · ready in 47s</span>
      </div>
    </div>
  );
}
